/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.6.2/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    java

    // Apply the application plugin to add support for building a CLI application
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
    mavenCentral()
    // maven { setUrl("https://plugins.gradle.org/m2/") }
}

dependencies {
    // This dependency is used by the application.
    implementation("com.google.guava:guava:28.0-jre")

    // Use JUnit test framework
    testImplementation("junit:junit:4.12")

    // https://mvnrepository.com/artifact/mysql/mysql-connector-java
    // compile group: "mysql", name: "mysql-connector-java", version: "8.0.17"
    implementation("mysql:mysql-connector-java:8.0.17")
}

application {
    // Define the main class for the application
    mainClassName = "poupex.App"
}
