/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loja.gui;

import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import loja.banco.tabelas.itens.ItemBean;
import loja.banco.tabelas.itens.ItemDAO;
import loja.banco.tabelas.pneus.PneuBean;
import loja.banco.tabelas.pneus.PneuDAO;
import loja.table_model.ItensTableModel;
import loja.uteis.FormataData;

/**
 *
 * @author mckatoo
 */
public class ItensGUI extends javax.swing.JFrame {

    /**
     * Creates new form ItensGUI
     */
    ItensTableModel model = new ItensTableModel();

    public ItensGUI() {
        initComponents();
        jTableItens.setModel(model);
        preencherTable();
        preencherCbPneus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtItem = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtSerie = new javax.swing.JTextField();
        cbPneu = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtQtde = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JFormattedTextField();
        jPanel5 = new javax.swing.JPanel();
        btnCadastrar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableItens = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Item"));

        jLabel1.setText("Número");

        jLabel2.setText("Série");

        jLabel3.setText("Item");

        jLabel4.setText("Pneu");

        txtItem.setNextFocusableComponent(txtQtde);
        txtItem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtItemFocusLost(evt);
            }
        });
        txtItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtItemKeyPressed(evt);
            }
        });

        txtNumero.setNextFocusableComponent(txtSerie);
        txtNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumeroFocusLost(evt);
            }
        });
        txtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumeroKeyPressed(evt);
            }
        });

        txtSerie.setNextFocusableComponent(cbPneu);
        txtSerie.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSerieFocusLost(evt);
            }
        });
        txtSerie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSerieKeyPressed(evt);
            }
        });

        cbPneu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um pneu" }));
        cbPneu.setNextFocusableComponent(txtItem);
        cbPneu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbPneuItemStateChanged(evt);
            }
        });
        cbPneu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbPneuFocusLost(evt);
            }
        });

        jLabel5.setText("Qtde");

        txtQtde.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtQtde.setNextFocusableComponent(txtPreco);
        txtQtde.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQtdeFocusLost(evt);
            }
        });
        txtQtde.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQtdeKeyPressed(evt);
            }
        });

        jLabel6.setText("Preço");

        txtPreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        txtPreco.setNextFocusableComponent(btnCadastrar);
        txtPreco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrecoFocusLost(evt);
            }
        });
        txtPreco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrecoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSerie, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbPneu, 0, 236, Short.MAX_VALUE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPreco, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(txtItem)
                    .addComponent(txtQtde))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbPneu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCadastrar.setBackground(new java.awt.Color(204, 204, 204));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setEnabled(false);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnAlterar.setBackground(new java.awt.Color(204, 204, 204));
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(204, 204, 204));
        btnExcluir.setForeground(new java.awt.Color(204, 0, 0));
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(255, 0, 0));
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnPesquisar.setBackground(new java.awt.Color(204, 204, 204));
        btnPesquisar.setText("Pesquisar | Listar Todos");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableItens.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jTableItens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableItensMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableItens);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        jMenu1.setText("Arquivo");

        jMenuItem4.setText("Configurações");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        menuSair.setText("Sair");
        menuSair.setName("menuSair"); // NOI18N
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenu1.add(menuSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Utilidades");

        jMenuItem1.setText("Notas Fiscais");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Clientes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Pneus");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSairActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        NotasGUI notaGUI = new NotasGUI();
//        notaGUI.setExtendedState(JFrame.MAXIMIZED_BOTH);
        notaGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        ConfiguracoesGUI configGUI = new ConfiguracoesGUI();
        configGUI.setVisible(true);
        configGUI.setAlwaysOnTop(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        PneusGUI pneuGUI = new PneusGUI();
//        pneuGUI.setExtendedState(JFrame.MAXIMIZED_BOTH);
        pneuGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jTableItensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableItensMouseClicked
        PneuBean pneu = (PneuBean) cbPneu.getSelectedItem();
        int linha = jTableItens.getSelectedRow();
        txtNumero.setText(jTableItens.getValueAt(linha, 0).toString());
        txtSerie.setText(jTableItens.getValueAt(linha, 1).toString());
        txtItem.setText(jTableItens.getValueAt(linha, 2).toString());
        txtQtde.setText(jTableItens.getValueAt(linha, 4).toString());
        txtPreco.setText(jTableItens.getValueAt(linha, 5).toString());
        verificarCampos();
        txtQtde.requestFocus();
    }//GEN-LAST:event_jTableItensMouseClicked

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        ItemDAO itemDAO = new ItemDAO();
        int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir " + txtNumero.getText() + "?", "Confirma exclusão?", JOptionPane.YES_NO_OPTION);
        if (confirma == 0 && !txtNumero.getText().isEmpty()) {
            try {
                int linhaSelecionada = jTableItens.getSelectedRow();
                if (linhaSelecionada != -1) {
                    itemDAO.excluir(Integer.parseInt(txtNumero.getText()));
                    model.removeRow(linhaSelecionada);
                }
            } catch (SQLException ex) {
                Logger.getLogger(ItensGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "É NECESSÁRIO SELECIONAR UM ITEM!");
        }
        limparCampos();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        int codPneu = Integer.parseInt(cbPneu.getSelectedItem().toString().split(" - ")[0]);
        ItemBean itemBean = new ItemBean();
        ItemDAO itemDAO = new ItemDAO();
        itemBean.setCodPneu(codPneu);
        itemBean.setQtde(Integer.parseInt(txtQtde.getText()));
        itemBean.setPreco(new BigDecimal(txtPreco.getText().replace(",", ".")));
        try {
            itemDAO.alterar(itemBean);
        } catch (SQLException ex) {
            Logger.getLogger(ItensGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        int linhaSelecionada = jTableItens.getSelectedRow();
        if (linhaSelecionada != -1) {
            model.setValueAt(txtNumero.getText(), linhaSelecionada, 0);
            model.setValueAt(txtSerie.getText(), linhaSelecionada, 1);
            model.setValueAt(txtItem.getText(), linhaSelecionada, 2);
            model.setValueAt(codPneu, linhaSelecionada, 3);
            model.setValueAt(txtQtde.getText(), linhaSelecionada, 4);
            model.setValueAt(txtPreco.getText().replace(",", "."), linhaSelecionada, 5);
        }
        limparCampos();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        int codPneu = Integer.parseInt(cbPneu.getSelectedItem().toString().split(" - ")[0]);
        ItemBean itemBean = new ItemBean();
        ItemDAO itemDAO = new ItemDAO();
        itemBean.setNumero(txtNumero.getText().toCharArray());
        itemBean.setSerie(txtSerie.getText().toCharArray());
        itemBean.setItem(Integer.parseInt(txtItem.getText()));
        itemBean.setCodPneu(codPneu);
        itemBean.setQtde(Integer.parseInt(txtQtde.getText()));
        itemBean.setPreco(new BigDecimal(txtPreco.getText().replace(",", ".")));
        try {
            itemDAO.inserir(itemBean);
        } catch (SQLException ex) {
            Logger.getLogger(ItensGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        limparCampos();
        model.addRow(itemBean);
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtSerieKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerieKeyPressed
        verificarCampos();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtItem.requestFocus();
        }
    }//GEN-LAST:event_txtSerieKeyPressed

    private void txtSerieFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSerieFocusLost
        verificarCampos();
    }//GEN-LAST:event_txtSerieFocusLost

    private void txtItemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemKeyPressed
        verificarCampos();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtQtde.requestFocus();
        }
    }//GEN-LAST:event_txtItemKeyPressed

    private void txtItemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemFocusLost
        verificarCampos();
    }//GEN-LAST:event_txtItemFocusLost

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ClientesGUI clienteGUI = new ClientesGUI();
//        clienteGUI.setExtendedState(JFrame.MAXIMIZED_BOTH);
        clienteGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void txtNumeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyPressed
        verificarCampos();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtItem.requestFocus();
        }
    }//GEN-LAST:event_txtNumeroKeyPressed

    private void txtNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroFocusLost
        verificarCampos();
    }//GEN-LAST:event_txtNumeroFocusLost

    private void cbPneuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbPneuFocusLost
    }//GEN-LAST:event_cbPneuFocusLost

    private void txtQtdeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQtdeFocusLost
        verificarCampos();
    }//GEN-LAST:event_txtQtdeFocusLost

    private void txtPrecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecoFocusLost
        verificarCampos();
    }//GEN-LAST:event_txtPrecoFocusLost

    private void txtQtdeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtdeKeyPressed
        verificarCampos();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cbPneu.requestFocus();
        }
    }//GEN-LAST:event_txtQtdeKeyPressed

    private void cbPneuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbPneuItemStateChanged
        verificarCampos();
        txtItem.requestFocus();
    }//GEN-LAST:event_cbPneuItemStateChanged

    private void txtPrecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecoKeyPressed
        verificarCampos();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtSerie.isEnabled()) {
                btnCadastrar.requestFocus();
            } else {
                btnAlterar.requestFocus();
            }
        }
    }//GEN-LAST:event_txtPrecoKeyPressed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        ItemDAO itensDAO = new ItemDAO();
        limparModal();
        if (txtNumero.getText().isEmpty() && txtSerie.getText().isEmpty() && (cbPneu.getSelectedIndex() == 0) && txtItem.getText().isEmpty() && txtQtde.getText().isEmpty() && txtPreco.getText().isEmpty()) {
            preencherTable();
        } else {
            if (!txtNumero.getText().isEmpty()) {
                for (ItemBean item : itensDAO.pesquisarPorNumero(txtNumero.getText().toCharArray())) {
                    model.addRow(item);
                }
                limparCampos();
                return;
            }
            if (!txtSerie.getText().isEmpty()) {
                for (ItemBean item : itensDAO.pesquisarPorSerie(txtSerie.getText().toCharArray())) {
                    model.addRow(item);
                }
                limparCampos();
                return;
            }
            if (cbPneu.getSelectedIndex() > 0) {
                int codPneu = Integer.parseInt(cbPneu.getSelectedItem().toString().split(" - ")[0]);
                itensDAO.pesquisarPorPneu(codPneu).forEach((item) -> {
                    model.addRow(item);
                });
                limparCampos();
                return;
            }
            if (!txtItem.getText().isEmpty() && txtItem.isValid()) {
                for (ItemBean item : itensDAO.pesquisarPorItem(txtItem.getText())) {
                    model.addRow(item);
                }
                limparCampos();
                return;
            }
            if (!txtQtde.getText().isEmpty() && txtQtde.isValid()) {
                for (ItemBean item : itensDAO.pesquisarPorQtde(txtQtde.getText())) {
                    model.addRow(item);
                }
                limparCampos();
                return;
            }
            if (!txtPreco.getText().isEmpty() && txtPreco.isValid()) {
                for (ItemBean item : itensDAO.pesquisarPorPreco(txtPreco.getText())) {
                    model.addRow(item);
                }
                limparCampos();
            }
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItensGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ItensGUI().setVisible(true);
        });
    }

    private void preencherTable() {
        ItemDAO itemDAO = new ItemDAO();
        limparModal();

        try {
            for (ItemBean item : itemDAO.listarTodos()) {
                model.addRow(item);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ItensGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void preencherCbPneus() {
        PneuDAO pneuDAO = new PneuDAO();

        try {
            for (PneuBean pneu : pneuDAO.listarTodos()) {
                cbPneu.addItem(pneu.toString());
            }
        } catch (SQLException ex) {
            Logger.getLogger(ItensGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        cbPneu.setSelectedIndex(0);
    }

    private void verificarCampos() {
        if (!txtNumero.getText().isEmpty() && !txtSerie.getText().isEmpty() && !txtItem.getText().isEmpty() && !txtQtde.getText().isEmpty() && !txtPreco.getText().isEmpty() && (cbPneu.getSelectedIndex() != -1)) {
            btnCadastrar.setEnabled(true);
            btnAlterar.setEnabled(true);
            btnExcluir.setEnabled(true);
        } else {
            btnCadastrar.setEnabled(false);
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);
        }
    }

    private void limparCampos() {
        txtNumero.setText("");
        txtSerie.setText("");
        txtItem.setText("");
        txtQtde.setText("");
        txtPreco.setText(null);
        cbPneu.setSelectedIndex(0);
        txtNumero.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<Object> cbPneu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableItens;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JTextField txtItem;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JFormattedTextField txtPreco;
    private javax.swing.JFormattedTextField txtQtde;
    private javax.swing.JTextField txtSerie;
    // End of variables declaration//GEN-END:variables

    private void limparModal() {
        for (int i = model.getRowCount() - 1; i > -1; i--) {
            model.removeRow(i);
        }
    }
}
