/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package estacionamento;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

import main.java.estacionamento.CarroBean;
import main.java.estacionamento.CarroDAO;
import main.java.estacionamento.Conexao;

public class App {
    public static void main(String[] args) throws SQLException {
        Connection con = Conexao.abrirConexao();
        CarroBean cb = new CarroBean();
        CarroDAO cd = new CarroDAO(con);

        // inserir carro 1
        cb.setPlaca("JDK2345");
        cb.setCor("Blue");
        cb.setDescricao("Carro 1");
        System.out.println(cd.inserir(cb));
        // inserir carro 2
        cb.setPlaca("JDY4125");
        cb.setCor("Red");
        cb.setDescricao("Carro 2");
        System.out.println(cd.inserir(cb));
        // inserir carro 3
        cb.setPlaca("KTR4589");
        cb.setCor("Black");
        cb.setDescricao("Carro 3");
        System.out.println(cd.inserir(cb));

        // listar todos
        List<CarroBean> lista = cd.listarTodos();
        if (lista != null) {
            for (CarroBean carro : lista) {
                System.out.println("PLACA: " + carro.getPlaca());
                System.out.println("COR: " + carro.getCor());
                System.out.println("DESCRIÇÃO: " + carro.getDescricao());
            }
        }

        // alterar
        cb.setPlaca("JDY4125");
        cb.setCor("Yellow");
        cb.setDescricao("Carro 2 modificado");
        System.out.println(cd.alterar(cb));

        // excluir
        cb.setPlaca("KTR4589");
        System.out.println(cd.excluir(cb));

        // listar todos
        List<CarroBean> listaFinal = cd.listarTodos();
        if (lista != null) {
            for (CarroBean carro : listaFinal) {
                System.out.println("PLACA: " + carro.getPlaca());
                System.out.println("COR: " + carro.getCor());
                System.out.println("DESCRIÇÃO: " + carro.getDescricao());
            }
        }
    }
}
